- hosts: all
  gather_facts: no
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80

  tasks:
  - name: Install nginx
    ansible.builtin.apt:
      name:
        - nginx
      state: present
      update_cache: yes
    become: yes

  - name: Update nginx index.html
    ansible.builtin.template:
      src: templates/index.html.j2
      dest: "{{root_dir}}/index.html"
    become: yes

  - name: Update nginx config
    ansible.builtin.template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx
    become: yes

  handlers:
  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
    become: yes
      