- hosts: all
  gather_facts: no
  
  tasks:
  - name: install git
    apt:
      name: git
      state: present
      update_cache: yes
    become: yes
    tags: git

  - name: install make
    apt:
      name: make
      state: present
      update_cache: yes
    become: yes
    tags: make

  - name: install nodejs
    apt:
      name: nodejs
      state: present
      update_cache: yesodejs
    become: yes
    tags: nodejs

  - name: Create users arya, sansa, tirion
    user: 
      name: '{{ item.name }}'
      state: present
      create_home: yes
    loop: 
      - { name: arya }
      - { name: sansa }
      - { name: tirion }
    become: yes
    tags: users
      
