- hosts: all
  
  tasks:
  - name: install git
    apt:
      state: present
      update_cache: yes
    become: yes

  - name: install make
    apt:
      state: present
      update_cache: yes
    become: yes
    tags: make

  - name: install js 
    apt:
      state: present
      update_cache: yes
    become: yes
    tags: nodejs

  - name: Create users arya, sansa, tirion
    ansible.builtin.user: 
      name: '{{ item.name }}'
      state: present
      loop: 
      - { name: arya }
      - { name: sansa }
      - { name: tirion }
      create_home: yes
      become: yes
      tags: users
      
